server:
    port: 8771

spring:
    application:
        name: serviceone
    zipkin:
        base-url: http://www.curvelife.cn:9411

    sleuth:
        sampler:
            probability: 1

